on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: dotnet build --configuration Release
  
  extract_version:
    name: Extract version
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Extract version from branch
      shell: bash
      run: echo "version=$(echo ${{ steps.extract_branch.outputs.branch }} | sed 's/^v//')" >> $GITHUB_OUTPUT
      id: extract_version

    - name: Print version
      shell: bash
      run: echo "${{steps.extract_version.outputs.version}} ${{steps.extract_branch.outputs.branch}}"
    
    - name: Set version
      run: echo "VERSION=${{steps.extract_version.outputs.version}}" >> $GITHUB_ENV
  
  use_version:
    name: Use version
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: extract_version
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set version
      run: echo "${{needs.extract_version.outputs.version}} ${{env.VERSION}}"    