on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: dotnet build --configuration Release
  
  extract_version:
    name: Extract version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Extract version from branch
      shell: bash
      run: echo "VERSION=$(echo ${{ steps.extract_branch.outputs.branch }} | sed 's/^v//')" >> version.env

  print_version:
    name: Print version
    needs: [extract_version]
    runs-on: ubuntu-latest
    steps:
    - name: Download version env
      uses: actions/download-artifact@v2
      with:
        name: version.env
    
    - name: Load version env
      shell: bash
      run: source version.env

    - name: Print version
      shell: bash
      run: echo "$VERSION"
    