on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: dotnet build --configuration Release
  
  extract_version:
    name: Extract version
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
      version: ${{ steps.extract_version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract branch name
      id: extract_branch
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

    - name: Extract version from branch
      id: extract_version
      run: echo "version=$(echo ${{ steps.extract_branch.outputs.branch }} | sed 's/^v//')" >> $GITHUB_OUTPUT

    - name: Print version
      run: echo "${{steps.extract_version.outputs.version}} ${{steps.extract_branch.outputs.branch}}"
      
  use_version:
    name: Use version
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: extract_version
    steps:
    - env:
        VERSION: ${{ needs.extract_version.outputs.version }}
      name: Print version
      run: echo "$VERSION"    