name: Assert Update Package

on:
  pull_request:
    branches:
      [
        uow,
        uow-abstractions,
        uow-efcore,
        uow-efcore-abstractions,
        uow-mongo,
        uow-mongo-abstractions,
      ]

env:
  DOTNET_VERSION: "8.0.x" # The .NET SDK version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Run build
        run: dotnet build --configuration Release

  check-pr-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check If PR Title Follows Semantic Versioning
        run: |
          PR_TITLE=$(echo "${{ github.event.pull_request.title }}")
          if [[ ! "$PR_TITLE" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Pull request title '$PR_TITLE' does not follow semantic versioning."
            exit 1
          fi

