on:
  push:
    branches:
    - main-UoW
jobs:
  Publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Locate to UoW core
      run: cd CQ.UnitOfWork.Core
    - name: Build
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output .
    - name: Push
      run: dotnet nuget push CQ.UnitOfWork.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
